-- ═══════════════════════════════════════════════════════════════════════════
-- טבלת price_list — מחירון המוסך
-- להריץ ב-Supabase → SQL Editor → Run
-- ═══════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.price_list (
  id          bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now(),
  category    text NOT NULL DEFAULT 'other',
  name        text NOT NULL,
  part_cost   numeric NOT NULL DEFAULT 0,
  sale_price  numeric NOT NULL DEFAULT 0,
  labor_cost  numeric NOT NULL DEFAULT 0,
  CONSTRAINT price_list_pkey PRIMARY KEY (id)
);

COMMENT ON COLUMN public.price_list.category IS 'oils | filters | brakes | engine | labor | other';
